version: '3'

services:

  # redis for backing cache service
  service_redis:
    image: redislabs/redismod:latest
    container_name: db_redis
    ports:
      - '6379:6379'
    volumes:
      - ~/docker/mongo-volume:/data/db

  #  main application stack
  hentry:
    image: 'yashkumarverma/hentry-server'
    container_name: hentry-server
    environment:
      REDIS_HOST: 'db_redis'
      REDIS_PORT: 6379
      PORT: 80
    depends_on:
      - service_redis

    ports:
      - '80:80'
