version: '3'

services:
  # redis for backing cache service
  service_redis:
    image: redislabs/redismod:latest
    container_name: db_redis
    ports:
      - '6379:6379'
    volumes:
      - ~/docker/mongo-volume:/data/db

  # feeder micro-service to feed data into timeseries database
  feeder:
    image: 'yashkumarverma/hentry-feeder'
    container_name: 'hentry-feeder'
    environment:
      PORT: 'db_redis:6379'
      REDIS_URL: 80 
    depends_on:
      - service_redis

  #  main application stack
  hentry:
    image: 'yashkumarverma/hentry-server'
    container_name: hentry-server
    environment:
      REDIS_HOST: 'db_redis'
      REDIS_PORT: 6379
      PORT: 80
    depends_on:
      - service_redis

    ports:
      - '80:80'
